[package]
name = "private_voting"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.1.2", directory="noir-projects/aztec-nr/aztec" }